// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8o0YDgLlYv0JzFHT3Wzy9gtPjWsrm4go',
    appId: '1:197369169653:web:888b0bdb083db405f167bc',
    messagingSenderId: '197369169653',
    projectId: 'safelane-34473',
    authDomain: 'safelane-34473.firebaseapp.com',
    storageBucket: 'safelane-34473.appspot.com',
    measurementId: 'G-ZPHRTE7QBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4msvR3e2pJCMDBSsNED39sFV7KQ08Q1g',
    appId: '1:197369169653:android:fb52ebc0bfecba74f167bc',
    messagingSenderId: '197369169653',
    projectId: 'safelane-34473',
    storageBucket: 'safelane-34473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDkk6tpOtclxgYMEhQUalcTdym37od1tE',
    appId: '1:197369169653:ios:2333b40180b6d357f167bc',
    messagingSenderId: '197369169653',
    projectId: 'safelane-34473',
    storageBucket: 'safelane-34473.appspot.com',
    iosClientId: '197369169653-0mp0dfqijvi11bm0h7va75e6bm0qll48.apps.googleusercontent.com',
    iosBundleId: 'com.example.safelane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDkk6tpOtclxgYMEhQUalcTdym37od1tE',
    appId: '1:197369169653:ios:2333b40180b6d357f167bc',
    messagingSenderId: '197369169653',
    projectId: 'safelane-34473',
    storageBucket: 'safelane-34473.appspot.com',
    iosClientId: '197369169653-0mp0dfqijvi11bm0h7va75e6bm0qll48.apps.googleusercontent.com',
    iosBundleId: 'com.example.safelane',
  );
}
